name: snex

on:
  push:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      run: ./do build

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          build

  test:
    name: Test
    needs:
      - build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build
        path: build

    - name: Debug
      run: ls -R

    - name: Test
      run: ./do test

